version: '3.1'
services:
  jup:
    image: jupyter/minimal-notebook
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan
    user: root
    command: jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=
